version: "3.3"

services:
  client:
    image: yopidev/broom-react:0.5.0
    networks:
      - web
    ports:
      - 80:80
    depends_on: 
      - redis
      - postgres
      - express

  express:
    image: yopidev/broom-express:0.5.0
    networks:
      - web
      - server
    ports:
      - 3064:3064
    depends_on: 
      - postgres
    env_file: back-end/.env.prod

  postgres:
    image: postgres:13-alpine
    networks:
      - server
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env.prod.db

  redis:
    image: redis:6.0.4-alpine
    networks:
      - server
    volumes:
      - redis_data:/data
    env_file: .env.prod.db

  mongo:
    image: mongo:4.2.7-bionic
    networks:
      - server
    ports: 
      - 27017:27017
    volumes: 
      - mongo_data:/data/db
    env_file: .env.prod.db

networks:
  web:
    driver: overlay
  server:
    driver: overlay

volumes:
  postgres_data:
  redis_data:
  mongo_data:
